# Model

1. Dividir el set de datos entre valores dependientes (y) e independientes (X). Y sería la columna
que se quiere predecir (“churn”).
2. Generar sets de testeo y entrenamiento.
3. ¿Es necesario escalar las features? Hacerlo si fuera necesario.
4. Probar por lo menos dos modelos y seleccionar uno. Explicar porque lo selecciono y qué
métricas uso para decidir.

<hr/>

In [66]:
# Libraries

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
plt.close("all")

import seaborn as sns

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, multilabel_confusion_matrix
from sklearn.preprocessing import StandardScaler


In [34]:
df_churn = pd.read_csv('../data/preprocessed/churn_preprocessed.csv')

In [35]:
df_churn.dtypes

Unnamed: 0.1          int64
Unnamed: 0            int64
customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure              float64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges        float64
Churn                object
dtype: object

In [13]:
df_churn.sample(5)

Unnamed: 0.1  Unnamed: 0  customerID  gender  SeniorCitizen Partner  \
6575          6575        6575  2978-XXSOG  Female              0      No   
2249          2249        2249  5527-ACHSO  Female              0      No   
113            113         113  4846-WHAFZ  Female              1     Yes   
5716          5716        5716  8903-XEBGX    Male              0      No   
5970          5970        5970  4853-OITSN    Male              0     Yes   

     Dependents  tenure PhoneService MultipleLines  ... DeviceProtection  \
6575         No    22.0          Yes           Yes  ...               No   
2249         No    11.0          Yes            No  ...               No   
113          No    37.0          Yes           Yes  ...               No   
5716        Yes     2.0          Yes            No  ...               No   
5970         No     5.0          Yes           Yes  ...               No   

     TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
6575         Yes          No              No  Month-to-month              Yes   
2249         Yes         Yes             Yes  Month-to-month               No   
113           No          No              No  Month-to-month              Yes   
5716          No          No             Yes  Month-to-month              Yes   
5970          No          No             Yes  Month-to-month              Yes   

         PaymentMethod MonthlyCharges TotalCharges Churn  
6575      Mailed check          59.05       1253.5    No  
2249      Mailed check          70.50        829.3    No  
113   Electronic check          76.50      2868.15   Yes  
5716  Electronic check          55.30       108.65    No  
5970  Electronic check          89.15       413.25    No  

[5 rows x 23 columns]

## Features selection

In [37]:
df_churn = df_churn.drop(['Unnamed: 0.1', 'Unnamed: 0', 'customerID'], axis=1)

### Train-test split

In [43]:
X = df_churn.drop('Churn', axis=1)
y = df_churn.Churn

In [53]:
X_train, X_test, y_train, y_test = train_test_split(X,y, stratify=y, random_state=12)

Churn = Yes shows same proportion of the dataframe before and after split x, y, train and test. It means that stratify= y is keeping proportions through dataframe splitting process.

In [54]:
df_churn.Churn.value_counts()['Yes'] / df_churn.shape[0]

0.26492042440318303

In [55]:
y_train.value_counts()['Yes'] / y_train.shape[0]

0.26480990274093724

In [56]:
y_test.value_counts()['Yes'] / y_test.shape[0]

0.26525198938992045

Dummies

In [57]:
X_train = pd.get_dummies(X_train, drop_first=True)
X_test = pd.get_dummies(X_test, drop_first=True)
X_train.sample(5)

SeniorCitizen  tenure  MonthlyCharges  TotalCharges  gender_Male  \
2321              0     4.0           85.65         338.9            1   
312               0    43.0          115.05        4895.1            0   
4562              0    61.0           79.80        4914.8            1   
2845              0    46.0           19.25         864.2            0   
5057              0     2.0           94.95         178.1            1   

      Partner_Yes  Dependents_Yes  PhoneService_Yes  \
2321            0               0                 1   
312             0               0                 1   
4562            1               0                 1   
2845            1               1                 1   
5057            0               0                 1   

      MultipleLines_No phone service  MultipleLines_Yes  ...  \
2321                               0                  1  ...   
312                                0                  1  ...   
4562                               0                  1  ...   
2845                               0                  0  ...   
5057                               0                  0  ...   

      StreamingTV_No internet service  StreamingTV_Yes  \
2321                                0                0   
312                                 0                1   
4562                                0                1   
2845                                1                0   
5057                                0                1   

      StreamingMovies_No internet service  StreamingMovies_Yes  \
2321                                    0                    1   
312                                     0                    1   
4562                                    0                    1   
2845                                    1                    0   
5057                                    0                    1   

      Contract_One year  Contract_Two year  PaperlessBilling_Yes  \
2321                  0                  0                     1   
312                   0                  1                     0   
4562                  1                  0                     1   
2845                  0                  1                     1   
5057                  0                  0                     0   

      PaymentMethod_Credit card (automatic)  PaymentMethod_Electronic check  \
2321                                      0                               1   
312                                       1                               0   
4562                                      0                               1   
2845                                      0                               0   
5057                                      0                               1   

      PaymentMethod_Mailed check  
2321                           0  
312                            0  
4562                           0  
2845                           1  
5057                           0  

[5 rows x 30 columns]

## Model

In [ ]:
# Instanciado del modelo

logistic_regression = LogisticRegression(penalty='none') # sin regularización
logistic_regression.fit(X_train, y_train);

In [59]:
y_test_pred = logistic_regression.predict(X_test)
y_test_pred

array(['No', 'Yes', 'No', ..., 'No', 'No', 'Yes'], dtype=object)

In [60]:
y_test_pred_proba = logistic_regression.predict_proba(X_test)
y_test_pred_proba

array([[0.97318928, 0.02681072],
       [0.42107385, 0.57892615],
       [0.61237735, 0.38762265],
       ...,
       [0.98441381, 0.01558619],
       [0.66592092, 0.33407908],
       [0.20667753, 0.79332247]])

In [61]:
accuracy_score(y_test, y_test_pred)

0.7937665782493368

In [62]:
confusion_matrix(y_test, y_test_pred)

array([[988, 120],
       [191, 209]])

In [63]:
logistic_regression.intercept_

array([-0.26550982])

In [64]:
logistic_regression.coef_

array([[ 1.63263288e-01, -5.54846107e-02,  6.73556403e-03,
         2.13185043e-04, -3.59964842e-02, -5.80328156e-03,
        -1.37306796e-01, -6.24025585e-01,  3.58515768e-01,
         2.82987186e-01,  7.81770932e-01, -7.31154438e-02,
        -7.31154438e-02, -4.52830445e-01, -7.31154438e-02,
        -2.30857054e-01, -7.31154438e-02, -1.19842828e-01,
        -7.31154438e-02, -3.93840283e-01, -7.31154438e-02,
         1.47298320e-01, -7.31154438e-02,  1.65960118e-01,
        -5.25781258e-01, -8.44376887e-01,  3.21548877e-01,
        -1.23583537e-01,  2.77466536e-01,  4.10135029e-03]])

### Regularización

In [67]:
scaler = StandardScaler()
scaler.fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [68]:
logistic_regression = LogisticRegression(penalty='l1', solver= 'liblinear')
logistic_regression.fit(X_train_scaled, y_train);

In [69]:
y_test_pred = logistic_regression.predict(X_test_scaled)
y_test_pred

array(['No', 'Yes', 'No', ..., 'No', 'No', 'Yes'], dtype=object)

In [70]:
accuracy_score(y_test, y_test_pred)

0.7970822281167109

In [71]:
confusion_matrix(y_test, y_test_pred)

array([[991, 117],
       [189, 211]])